(with-open-file (in "../input.txt")
  (let ((str (read-line in))
	(counter 0)
	(idx 0)
	(entered-p nil))
    (map nil #'(lambda (c)
		 (cond ((eq c #\() (incf counter))
		       ((eq c #\)) (decf counter))
		       (t t))
		 (incf idx)
		 (if (and (= counter -1) (not entered-p))
		     (progn
		       (format t "Basement entered at index ~a~%" idx)
		       (setf entered-p t))))
	 str)
    counter))
